Update first-actions.yml

diff --git a/.github/workflows/first-actions.yml b/.github/workflows/first-actions.yml
--- a/.github/workflows/first-actions.yml
+++ b/.github/workflows/first-actions.yml
@@ -12,6 +12,7 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
+
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
@@ -22,7 +23,17 @@ jobs:
         python -m pip install --upgrade pip
         pip install pytest
 
+    - name: Check if src directory exists
+      run: |
+        if [ -d "src" ]; then
+          echo "src directory exists."
+        else
+          echo "Error: src directory does not exist."
+          exit 1
+        fi
+
     - name: Run tests
       run: |
         cd src
         python -m pytest addition.py
+
